spring:
  datasource:
    url: jdbc:mysql://localhost:3306/command_pattern?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace